master:
  build: ./master
  command: spark-class org.apache.spark.deploy.master.Master -h master
  hostname: master
  environment:
    MASTER: spark://master:7077
    SPARK_PUBLIC_DNS: localhost
  expose:
    - 7077
    - 8080
  ports:
    - 7077:7077
    - 8080:8080

worker1:
  build: ./worker
  command: spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
  hostname: worker1
  environment:
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_MEMORY: 2g
    SPARK_WORKER_PORT: 8881
    SPARK_WORKER_WEBUI_PORT: 8081
    SPARK_PUBLIC_DNS: localhost
  links:
    - master
  expose:
    - 8881
    - 8081
  ports:
    - 8081:8081
    - 8881:8881

worker2:
  build: ./worker
  command: spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
  hostname: worker2
  environment:
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_MEMORY: 2g
    SPARK_WORKER_PORT: 8882
    SPARK_WORKER_WEBUI_PORT: 8082
    SPARK_PUBLIC_DNS: localhost
  links:
    - master
  expose:
    - 8882
    - 8082
  ports:
    - 8082:8082
    - 8882:8882