master:
  build: ./master
  container_name: scalarecommender_master_1
  command: spark-class org.apache.spark.deploy.master.Master -h master
  hostname: master
  environment:
    MASTER: spark://master:7077
    SPARK_PUBLIC_DNS: localhost
  expose:
    - 7077
    - 8080
  ports:
    - 7077:7077
    - 8080:8080

worker:
  build: ./worker
  command: spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
  hostname: worker1
  environment:
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_MEMORY: 2g
    SPARK_WORKER_PORT: 8881
    SPARK_WORKER_WEBUI_PORT: 8081
    SPARK_PUBLIC_DNS: localhost
  links:
    - master
  expose:
    - 8881
  ports:
    - "8081"